### ISSUE TITLE
Brug af ejerregister data

### ISSUE THREAD

**Issue by anderspeders** [antongrau/soc.elite#8]
Har I overvejet at matche personer i elitenetvaerket med personer registreret i ejerregistret hos CVR (https://datacvr.virk.dk/data/cvr)? Det kunne muligvis bidrage til yderligere baggrund om graden af erhvervsaktiviteter hos erhvervsaktive.

**Comment by antongrau** [comment]
Vi er allerede igang. Vi har koblet og suget en del fra CVR-registreret og har lige netop nu lavet et udtræk fra ejerdelen også. Dog tror jeg ikke at den offentlige adgang er på niveau med hvad styrelsen har liggende. Hvis du er interesseret i at bruge pakken så bemærk at jeg har flyttet udviklingen over til "eliter" pakken istedet.
