### ISSUE TITLE
qlcMatrix er ikke længere i CRAN

### ISSUE THREAD

**Issue by jeppebundsgaard** [antongrau/soc.elite#9]
Tak for fantastisk oplæg ved dagens workshop.

Ved installation får jeg fejl for qlcMatrix fordi den ikke længere er i CRAN
Man kan løse problemet ved at installere herfra:
`devtools::install_github("cysouw/qlcMatrix")`

Og så skal man kalde 
`library(soc.elite)`
før data(den)

**Comment by antongrau** [comment]
Hej Jeppe,

Tak for heads up - soc.elite pakken er efterfulgt af eliter pakken, som faktisk også var påvirket af qlcMatrix problemet. Men nu er det fixet!

- Anton
